# Replace the text below to customize your site
site_name: HBO-ICT SpaceInvaders
site_description: Documentation for Game Development project
site_author: <student name here>
copyright: Copyright <year> GD <student name here>

site_url: https://localhost:8000/

extra_javascript:
  - js/p5.min.js
  - js/p5.sound.js

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors

    - scheme: default
       # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
      primary: light-blue
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light-blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    # See available fonts at https://fonts.google.com/
    text: Open Sans
    code: Ubuntu Mono
  icon:
    logo: material/space-invaders
  favicon: images/space-invaders.svg
  features:
    - content.code.annotate

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
